### ISSUE TITLE
Decide if attributes should be generated and if so - generate them

### ISSUE THREAD

**Issue by Albert221** [leancodepl/corelibrary#186]
Currently, the contracts generator generates custom [attributes] that often extend `AuthorizeWhenAttribute` (and hence expect this class to exist). This makes it a little inconvenient to provide this class for each contracts generated file while it's never used on frontends.

This occurs in the Dart generator. I don't have the knowledge of the TypeScript generator.

**Comment by jakubfijalkowski** [comment]
That's expected behavior I think - client is requested to provide both `IRemoteQuery`/`IRemoteCommand` and well-known custom attributes. Deciding _by convention_ that something is unnecessary is IMO bad - you might miss necessary information.

**Comment by Albert221** [comment]
IMHO attributes aren't something to be _leaked_ out of the backend context. In our use-cases, it usually tells the contract generator to omit certain stuff (`[ExcludeFromGeneration]`) or how to authorize the user (`[Authorize*]`). I don't see how the attributes are relevant.

Also, isn't this transport part of the CQRS pattern only about exchanging the data/payloads and not leaking this type of stuff? I may be wrong on this though.

> you might miss necessary information

Do you have some real-life example maybe?

**Comment by jakubfijalkowski** [comment]
I might be missing something - you mean generating _types_ (e.g. `AuthorizeWhenOwnsOrderAttribute`) or generating attribute applications (i.e. `[AuthorizeWhenOwnsOrderAttribute]` on `OrderById` query)?

If the second option - this should be preserved. It's part of the API contract. Example - authorization. Client has to know when particular endpoint can be called as it might be vital for correct usage. And the first option is required for the second one to work if we want to preserve types correctly.

I think it is a bug that the attributes are not (are they?) generated in the first place. 

> isn't this transport part of the CQRS

This isn't transport part. This has more to do with REST and GraphQL than CQRS. The "contracts" are really our IDL that describe the API surface and should be treated exclusively as IDL. CQRS is a pattern and not something you have to transport - it's just that our API behaves in CQRS-y way but it still is "just" an API.

**Comment by Albert221** [comment]
Given this contract:

```csharp
    [AuthorizeWhenHasAnyOf(Roles.User)]
    [WhenOwnsAuctionOrDoesNotExist]
    public class CancelAuction : IRemoteCommand, IAuctionRelated
    {
        public Guid AuctionId { get; set; }
        public static class ErrorCodes
        {
            public const int AuctionDoesNotExist = 1;
            public const int AuctionAlreadyEnded = 2;
        }
    }
```

and this attribute:

```csharp
    public interface WhenOwnsAuctionOrDoesNotExist { }

    public class WhenOwnsAuctionOrDoesNotExistAttribute : AuthorizeWhenAttribute
    {
        public WhenOwnsAuctionOrDoesNotExistAttribute()
            : base(typeof(WhenOwnsAuctionOrDoesNotExist))
        {
        }
    }
```

I'll have those Dart classes generated:

```dart
@JsonSerializable()
class CancelAuction implements IRemoteCommand {
  CancelAuction();

  factory CancelAuction.fromJson(Map<String, dynamic> json) =>
      _$CancelAuctionFromJson(json);

  @JsonKey(name: 'AuctionId')
  String auctionId;

  @override
  String getFullName() => 'X.Core.Contracts.Auctions.CancelAuction';

  @override
  Map<String, dynamic> toJson() => _$CancelAuctionToJson(this);
}

@JsonSerializable()
class CancelAuctionErrorCodes {
  CancelAuctionErrorCodes();

  factory CancelAuctionErrorCodes.fromJson(Map<String, dynamic> json) =>
      _$CancelAuctionErrorCodesFromJson(json);

  static const int auctionDoesNotExist = 1;
  static const int auctionAlreadyEnded = 2;

  Map<String, dynamic> toJson() => _$CancelAuctionErrorCodesToJson(this);
}

@JsonSerializable()
class WhenOwnsAuctionOrDoesNotExist {
  WhenOwnsAuctionOrDoesNotExist();

  factory WhenOwnsAuctionOrDoesNotExist.fromJson(Map<String, dynamic> json) =>
      _$WhenOwnsAuctionOrDoesNotExistFromJson(json);

  Map<String, dynamic> toJson() => _$WhenOwnsAuctionOrDoesNotExistToJson(this);
}

@JsonSerializable()
class WhenOwnsAuctionOrDoesNotExistAttribute extends AuthorizeWhenAttribute {
  WhenOwnsAuctionOrDoesNotExistAttribute();

  factory WhenOwnsAuctionOrDoesNotExistAttribute.fromJson(
          Map<String, dynamic> json) =>
      _$WhenOwnsAuctionOrDoesNotExistAttributeFromJson(json);

  @override
  Map<String, dynamic> toJson() =>
      _$WhenOwnsAuctionOrDoesNotExistAttributeToJson(this);
}
```

I don't see any value in having those `WhenOwnsAuctionOrDoesNotExistAttribute` and `WhenOwnsAuctionOrDoesNotExist` classes generated. They're not even anyhow connected to the `CancelAuction` command in the Dart code and they add some volume to the contracts file and require the developers to provide the `AuthorizeWhenAttribute` class even though it's used absolutely nowhere in the Dart frontend.

**Comment by jakubfijalkowski** [comment]
> hey're not even anyhow connected to the CancelAuction command in the Dart code

This is the real bug. They should be connected this way or another - otherwise you're missing the context (which did make problems in the past for us).

> they add some volume to the contracts file and require the developers to provide the AuthorizeWhenAttribute class

The volume is negligible as is providing `AuthorizeWhenAttribute`.
