### ISSUE TITLE
Fetch FCM tokens for multiple users in a single query

### ISSUE THREAD

**Issue by mchudy** [leancodepl/corelibrary#189]
In `IPushNotificationTokenStore`

```csharp
public Task<Dictionary<string, List<string>>> GetTokensAsync(
    IEnumerable<Guid> userIds,
    CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by jakubfijalkowski** [comment]
Duplicate of #92?

**Comment by mchudy** [comment]
Not quite, those are on different levels of abstraction. `SendToMultipleUsersAsync` is a nice shortcut, but it won't work with localized notifications (when you need to send one `MulticastMessage` for each locale). But I guess they both address the same problem (with this one giving some more elasticity). Depends on how many convenience methods we want to have in the core lib really.
