### ISSUE TITLE
`CancellationToken`s in pipelines

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/corelibrary#24]
Currently, we're ignoring `CancellationToken`s in HTTP/event pipelines. It would be good to support them.

I see two options:
1. Pass `CancellationToken` in context. This is IMO preferred approach as it will mimic what we have in ASP.NET Core's `HttpContext`. It will be also easier to migrate to as it will _just_ require changes in a couple of places.
2. Pass it explicitly through execution calls. This will effectively force change in almost every file that touches pipelines, so... :)

**Comment by marcin-dardzinski** [comment]
Yes, I'd also go with the first option. It fits the concept of cross cutting concerns handled by the context.

**Comment by marcin-dardzinski** [comment]
If no one has any objections, I might take it and do it this or next week, following the first option.

**Comment by marcin-dardzinski** [comment]
I did a simple implementation, adding cancellation directly to the pipeline + EF Core repositories.
https://github.com/leancodepl/corelibrary/compare/feature/cancellation-tokens

For each of the elements, I don't think they need special treatment, with the exception of `EventsPublisherElement` and `EventsExecutorElement`. By the way, do we want to change `IDomainEventHandler` interface to support cancellation tokens. It would be quite a breaking change (note that there are some breaking changes already).

I don't know if this is already PR worthy, or we'd like to cover _almost_ everything now, with one PR

**Comment by jakubfijalkowski** [comment]
I'm not sure whether we should cancel publishing events if the task has been canceled mid-publish. The event will be stored in the DB but still - part of the process will be aborted by external factors (HTTP connection closed most of the time).

The same applies to `IDomainEventHandler` - it should be executed no matter what. So I think there is no need to add cancellation token there. Also, I think we should ditch this completely and go with MT even for in-proc communication.

Btw. I think we should handle cancellation better in the `RemoteCQRSHandler` middleware - abort the process when needed but don't throw exceptions in queries (just log warning) if the request is aborted when serializing response.

**Comment by marcin-dardzinski** [comment]
Following up our offline discussion with @jakubfijalkowski 
1. Publishing events (via MassTransit) will be subject to cancellation, as the events are transactionally saved to the database and it's publishing will be later retried. 
2. There will be no cancellation in `IDomainEventHandlers`, as they're not persisted anywhere, so they have to be executed no matter what. Also, they'll be a deprecated approach.
3. Cancellation handling in `RemoteCQRSHandler` has to be added.
