### ISSUE TITLE
Cannot override database connection string environment key

### ISSUE THREAD

**Issue by lukaszgarstecki** [leancodepl/corelibrary#288]
The key value in override configuration is hardcoded: https://github.com/leancodepl/corelibrary/blob/84d3929b0ee5d5709d9b891019b061c4a20e6e71/src/Testing/LeanCode.IntegrationTestHelpers/ConfigurationOverrides.cs#L65
It should be configurable :see_no_evil:

**Comment by Saancreed** [comment]
Also here: https://github.com/leancodepl/corelibrary/blob/18348aa7bda9d3d2695fad2ea1438b7d799ed816/src/Core/LeanCode.Components.Startup/IHostBuilderExtensions.cs#L18-L21
