### ISSUE TITLE
`Stream` result in query

### ISSUE THREAD

**Issue by marcin-dardzinski** [leancodepl/corelibrary#312]
There are sometimes cases when we have to generate and return files (eg. csv/pdf) in queries. Currently remote cqrs cannot do this natively and we have two options:
1) Return the result as base64/plaintext in a json response
2) Save the generated file in blob storage and return the link to the file (note that it sometimes may be desired, e.g. if we'd like to persist/track exports).

I'd like to do sth like:
```
public class ExportUsersToCsv : IRemoteQuery<Stream>
{ }
```

This method itself generates new prob... opportunites, e.g.
1) Setting the content type of the response, but we can solve it by custom attribute `ContentType("application/csv")` + a roslyn analyzer to enforce it.
2) Updating client libraries and contracts generator to understand such endpoints.

I don't find it a very urgent feature, but once in a while I feel I could use it.

**Comment by jakubfijalkowski** [comment]
I... I _think_ I'm still against that. Let's keep the CQRS simple, without streaming features that introduce a horde of new problems.

**Comment by jakubfijalkowski** [comment]
Closing, as the discussion on this feature will be done in a [contractsgenerator](https://github.com/leancodepl/contractsgenerator) context.
