### ISSUE TITLE
Move `GetColumnName` and `GetFullTableName` to a shared project

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/corelibrary#359]
They are used in a couple of projects. It is high time to share it.

Related: PR #358

**Comment by Saancreed** [comment]
Would `LeanCode.Dapper` be a good place for them?

**Comment by jakubfijalkowski** [comment]
Hmmm... Considering that these two methods are used mostly in Dapper queries, I think that is a good idea.

**Comment by Saancreed** [comment]
Done, see 74f7eae0ce1e6033a1a8784a07338446b840092e.
