### ISSUE TITLE
Blob garbage collection

### ISSUE THREAD

**Issue by lukaszgarstecki** [leancodepl/corelibrary#380]
In our projects we frequently use user generated blobs (fir example profile pictures). 

Usually when client apps want to upload blob, our server  generates new upload link with time limited token, where client app can upload the blob. After successful upload server is notified by the client that the file was uploaded. 

This approach may result in a situation where client uploaded the blob, but did not confirmed that fact to the server. 

In order to address that case we want to prepare dedicated module that collects all leased links for blob upload and periodically removes the data uploaded to links that were leased an not confirmed.

We want the module to require minimal developer attention (if possible).

**Comment by jakubfijalkowski** [comment]
This can be done using [Blob Lifecycle Management](https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview) directly on Azure & a proper tag mgmt on backend.

The question is if we want to make that part of the framework or not - this boils down to basically two lines of code (`CreateBlob` + `SetProperties`) and some glue to wire up when the blob is really used, which will be hard to abstract away.

**Comment by jakubfijalkowski** [comment]
Yeah, after thorough investigation, we should start with docs only, so basically we should write down:
1) How to configure blob storage so that "not used" blobs are deleted automatically ([Blob Lifecycle Management](https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview))
2) How the API should look like (in general) and what should it do as part of the call.

The rough draft for (1) looks like this:

<details><summary>Details</summary>
<p>

```terraform
resource "azurerm_storage_management_policy" "rules" {
  storage_account_id = azurerm_storage_account.main_storage.id

  rule {
    name    = "delete_unused_blobs"
    enabled = true
    filters {
      prefix_match = ["${azurerm_storage_container.container.name}/"] # Container name
      blob_types   = ["blockBlob"]
      match_blob_index_tag {
        name      = "ToDelete" # This is the tag name that needs to be set to an empty blob when generating the link
        operation = "=="
        value     = "1"
      }
    }
    actions {
      base_blob {
        delete_after_days_since_modification_greater_than = 7
      }
    }
  }
}
``` 

</p>
</details>
