### ISSUE TITLE
Don't force `dbContext.Update` in `EFRepository`

### ISSUE THREAD

**Issue by marcin-dardzinski** [leancodepl/corelibrary#409]
Currently [`EFRepository.Update`](https://github.com/leancodepl/corelibrary/blob/d4e10dce69d1c327b75770488b71b88c4c99943a/src/Domain/LeanCode.DomainModels.EF/EFRepository.cs#L63) method calls a `dbContext.Update` method as a part of it's procedure. 
IMO, this is an overkill, it forces all the properties of an entity to be written to the database, while it could send only those that really changed. 
I suggest we make this method only bump `DateModified` for `IOptimisiticConcurrency` instances and let EF do it's job.

**Comment by jakubfijalkowski** [comment]
What about non-optimistic entities? This will drastically change the behavior (which might be good) - now, if you make a noop action on an entity, you will not call the database at all (that might have side effects).

**Comment by marcin-dardzinski** [comment]
Well, not at all. Right now it'll force EF to update all the properties of an entity (I don't remember how about navigation properties). If sth changes (or there will be other entities tracked, like inbox/outbox) and you call `SaveChangesAsync` there will be a call to db. If nothing changes and there will be no call to the db, then what are the side effects that you're talking about?

**Comment by jakubfijalkowski** [comment]
> If nothing changes and there will be no call to the db, then what are the side effects that you're talking about?

Exactly that call - the one that seemingly does nothing. It _should_ be a noop, but it might not be if someone added triggers or there is some auto-regenerated property. This _is_ bad design IMO, but if that is used and we change the behavior, it will break in a very naughty way.
