### ISSUE TITLE
Publish to internal feed only

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/corelibrary#47]
Currently we're publishing _all_ versions to NuGet and the feed looks [rather bad](https://www.nuget.org/packages/LeanCode.Components) and is quite unusable.

Consider Dependabot's PRs - it creates one PR per dependency and that results in a couple of PRs merged at once. Moreover, we tend to break main branch temporarily (e.g. two consecutive PRs) and publishing everything makes using our library painful.

I propose to publish everything to public Feedz feed "just in case" and publish to NuGet only the versions that we manually mark as "publishable".

**Comment by marcin-dardzinski** [comment]
We could use tags or releases to trigger pushing to nuget. Maybe instead of Feedz we can use build artifacts to store generated nupkgs, but both options are OK for me

**Comment by jakubfijalkowski** [comment]
I would be all for Github Packages but
> **You need an access token** to publish, **install**, and delete packages in GitHub Packages. You can use a personal access token to authenticate with your username directly to GitHub Packages or the GitHub API. You can use a GITHUB_TOKEN to authenticate using a GitHub Actions workflow.
-- [Source](https://help.github.com/en/packages/publishing-and-managing-packages/about-github-packages#about-tokens)

That would somewhat defeat the point if someone wants to be on the bleeding edge.

**Comment by marcin-dardzinski** [comment]
I didn't mean GH packages, but action artifacs, https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts.
It doesn't allow nugget api access and has 90 days retention period, but as far as I understood still nuget will be the ultimate source for our projects.

**Comment by jakubfijalkowski** [comment]
Yeah, I think you're right. Feedz feed might be slightly easier to use but probably it won't be that usable.
