### ISSUE TITLE
More 5.0 breaking changes

### ISSUE THREAD

**Issue by Saancreed** [leancodepl/corelibrary#67]
Rough TODO list:

* ~Ensure method names returning awaitables end with `Async` (mostly `TaskScheduler` stuff). (#83)~
* ~Remove `IdentityProvider` (use `Guid.NewGuid()` directly)~ This one will stay here.
* ~Rename `TimeProvider.Time` to avoid collisions with `System.Time`. (#111)~
* Replace `LeanCode.SmsSender` with `LeanCode.SmsApi` using their .NET client library.
* ~Remove `IDomainEventHandler` (enforce usage of MassTransit).~
* [IdentityServer 4](https://github.com/leancodepl/corelibrary/issues/67#issuecomment-656151516)
* …that's all for now I think?

**Comment by jakubfijalkowski** [comment]
IdentityServer 4 - I forgot about that. We need to adjust KV service and remove our Persistent Grant store.

**Comment by jakubfijalkowski** [comment]
BTW. I think we should split this issue into separate ones so that we have easier tracking.
