### ISSUE TITLE
Remove outdated components

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/corelibrary#73]
We have some components that we are no longer using (or at least shouldn't use):
1. `LeanCode.PushNotifications` & `LeanCode.PushNotifications.EF`,
2. `LeanCode.IdentityServer.PersistedGrantStore` (we can use IS-provided one now),
3. `LeanCode.DomainModels.EventsExecution` - this will be trickier since MT integration relies on it somewhat,
4. `LeanCode.IdentityProvider` - ?
5. Anything else?

**Comment by marcin-dardzinski** [comment]
> 3\. `LeanCode.DomainModels.EventsExecution` - this will be trickier since MT integration relies on it somewhat,

I guess all the necessary stuff can be moved to Mass Transit integration project. By the way, do we want to keep `EventsInterceptorElement` and having events carried in context, or capture them directly in the event raising elements?


> 4\. `LeanCode.IdentityProvider` - ?

I'd keep it

> 5\. Anything else?

~`LeanCode.UrlHelper` seems like a useless piece of code.~ EDIT: Okay, it's used :stuck_out_tongue:

**Comment by jakubfijalkowski** [comment]
> By the way, do we want to keep EventsInterceptorElement and having events carried in context, or capture them directly in the event raising elements?

I think that my idea to keep the events in context was terrible. It gives us nothing and just makes the interactions hellishly indirect and requires some stupid bookkeeping.
![Fire](http://www.reactiongifs.com/r/fire.gif)

**Comment by jakubfijalkowski** [comment]
Another one: `LeanCode.PdfGenerator`. I think we should remove it and use PdfRocket the same way we use SendGrid - without interface.

**Comment by marcin-dardzinski** [comment]
Well, for pdfs first we have to rework the PdfRocket client, so I'd make it a separate issue/PR

**Comment by marcin-dardzinski** [comment]
Do we want to make a direct dependency from `LeanCode.CQRS.Default` to `LeanCode.DomainEvents.MassTransitRelay` and put MT related elements to default pipeline (which one - with or without outbox?)? Do we remove event handling from default pipeline? I'd say we remove the `CQRS.WithDefaultPipelines` method and force users to think what they want to use (I think most of the projects still use custom pipelines).

**Comment by jakubfijalkowski** [comment]
Yeah, the defaults resulted in no defaults being used almost anywhere. That only introduced coupling that hasn't been really used.

I'm also thinking about integrating `LeanCode.CQRS.Default` into `LeanCode.CQRS.Execution` - they mostly serve the same purpose now and they're companion packages that can't really work. I think the idea behind `Default` was to separate Autofac- from pipeline-based parts but I don't know whether that gives us anything meaningful now, since our reliance on Autofac is very high.
